# fly.toml app configuration file generated for algora-media on 2024-02-08T18:25:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'algora-media'
primary_region = 'lax'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  DNS_CLUSTER_QUERY = 'algora-media.internal'
  PRIMARY_REGION = 'lax'
  PHX_HOST = 'tv.algora.io'
  PORT = '4000'

[mounts]
  source="algora_media_tmp"
  destination="/data"

[[services]]
  protocol = 'tcp'
  internal_port = 4000
  processes = ['app']

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100000
    soft_limit = 2000

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '20s'

[[services]]
  protocol = 'tcp'
  internal_port = 4001
  processes = ['app']

[[services.ports]]
    port = 81
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 444
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100000
    soft_limit = 10000

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '20s'

[[services]]
  protocol = 'tcp'
  internal_port = 9006
  processes = ['app']

[[services.ports]]
    port = 9006

  [services.concurrency]
    type = 'connections'
    hard_limit = 100000
    soft_limit = 10000


[deploy]
  strategy = "rolling"
  max_unavailable = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"

# ... rest of your configuration ...

